"""
setup.py — Run this ONCE to configure your ComplianceAI platform
=================================================================
Does 3 things:
  1. Creates your .env file interactively
  2. Resets the seen_publications table so you get fresh results
  3. Tests all sources to show you what's working

Run: python setup.py
"""
import os
import sys
import sqlite3

def create_env():
    print("\n" + "="*60)
    print("  ComplianceAI — First Time Setup")
    print("="*60)

    env_path = ".env"

    # Check if .env already exists
    existing = {}
    if os.path.exists(env_path):
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if "=" in line and not line.startswith("#"):
                    k, v = line.split("=", 1)
                    existing[k.strip()] = v.strip()
        print(f"\n✅ Found existing .env with {len(existing)} settings")

    print("\n📋 Let's configure your API keys.\n")
    print("   Press ENTER to keep existing value, or type a new one.\n")

    config = {}

    # Gemini API Key
    existing_gemini = existing.get("GEMINI_API_KEY", "")
    display = f" [{existing_gemini[:8]}...]" if existing_gemini else ""
    print(f"1. GEMINI API KEY{display}")
    print("   Free at: https://aistudio.google.com → Get API Key")
    val = input("   Enter key: ").strip()
    config["GEMINI_API_KEY"] = val if val else existing_gemini

    print()

    # Gmail
    existing_gmail = existing.get("GMAIL_USER", "")
    display = f" [{existing_gmail}]" if existing_gmail else ""
    print(f"2. GMAIL ADDRESS{display}")
    print("   Your Gmail address (e.g. yourname@gmail.com)")
    val = input("   Enter Gmail: ").strip()
    config["GMAIL_USER"] = val if val else existing_gmail

    print()

    # Gmail App Password
    existing_pass = existing.get("GMAIL_APP_PASSWORD", "")
    display = " [already set]" if existing_pass else ""
    print(f"3. GMAIL APP PASSWORD{display}")
    print("   NOT your Gmail password — a special 16-character code")
    print("   Get it: myaccount.google.com → Security → 2-Step Verification → App passwords")
    print("   Select 'Mail' and 'Mac' → Generate → copy the 16 characters")
    val = input("   Enter app password: ").strip()
    config["GMAIL_APP_PASSWORD"] = val if val else existing_pass

    print()

    # TO_EMAIL
    existing_to = existing.get("TO_EMAIL", "")
    display = f" [{existing_to}]" if existing_to else ""
    print(f"4. RECIPIENT EMAIL{display}")
    print("   Who should receive the daily digest? (can be same as Gmail)")
    val = input("   Enter email: ").strip()
    config["TO_EMAIL"] = val if val else existing_to or config.get("GMAIL_USER", "")

    # Optional: Anthropic key
    print()
    existing_anthropic = existing.get("ANTHROPIC_API_KEY", "")
    display = f" [{existing_anthropic[:8]}...]" if existing_anthropic else " [optional - skip if using Gemini]"
    print(f"5. ANTHROPIC API KEY{display} (optional)")
    print("   Only needed if you want Claude instead of Gemini")
    print("   Get free $5 credit at: console.anthropic.com")
    val = input("   Enter key (or press ENTER to skip): ").strip()
    config["ANTHROPIC_API_KEY"] = val if val else existing_anthropic

    # Optional: Slack
    print()
    existing_slack = existing.get("SLACK_WEBHOOK_URL", "")
    display = " [already set]" if existing_slack else " [optional - skip for now]"
    print(f"6. SLACK WEBHOOK{display} (optional)")
    print("   Get from: api.slack.com/apps → Incoming Webhooks")
    val = input("   Enter webhook URL (or press ENTER to skip): ").strip()
    config["SLACK_WEBHOOK_URL"] = val if val else existing_slack

    # Write .env
    with open(env_path, "w") as f:
        f.write("# ComplianceAI — Environment Variables\n")
        f.write("# Generated by setup.py\n\n")
        for key, value in config.items():
            if value:
                f.write(f"{key}={value}\n")

    print(f"\n✅ .env file created at: {os.path.abspath(env_path)}")
    return config


def reset_seen_publications():
    """Clear the seen_publications table so fresh results come through."""
    db_path = "database/complianceai.db"
    if not os.path.exists(db_path):
        print("  ℹ️  No database yet — will be created on first run")
        return

    conn = sqlite3.connect(db_path)
    count = conn.execute("SELECT COUNT(*) FROM seen_publications").fetchone()[0]
    conn.execute("DELETE FROM seen_publications")
    # Also reset is_new flag
    conn.execute("UPDATE publications SET is_new=0")
    conn.commit()
    conn.close()
    print(f"\n✅ Reset {count} seen publications — next run will re-analyze everything fresh")


def test_sources():
    """Quick test of all scraping sources."""
    print("\n" + "="*60)
    print("  Testing regulatory sources...")
    print("="*60)

    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    try:
        from agents.scraper import (
            fetch_occ, fetch_fincen, fetch_naic,
            fetch_federal_register, fetch_sec,
            fetch_california_doi, fetch_nydfs
        )
        tests = [
            ("OCC",              fetch_occ),
            ("FinCEN",           fetch_fincen),
            ("NAIC",             fetch_naic),
            ("Federal Register", fetch_federal_register),
            ("SEC",              fetch_sec),
            ("CA DOI",           fetch_california_doi),
            ("NYDFS",            fetch_nydfs),
        ]
        total = 0
        print()
        for name, fn in tests:
            results = fn()
            status = "✅" if len(results) > 0 else "⚠️ "
            print(f"  {status} {name}: {len(results)} items")
            if results:
                print(f"     Sample: {results[0]['title'][:65]}...")
            total += len(results)
        print(f"\n  Total: {total} publications found across all sources")
    except Exception as e:
        print(f"  ⚠️  Could not test sources: {e}")


def main():
    # Step 1: Create .env
    config = create_env()

    # Step 2: Reset seen publications
    print("\n" + "="*60)
    print("  Resetting database...")
    print("="*60)
    reset_seen_publications()

    # Step 3: Test sources
    print("\n" + "="*60)
    print("  Testing all regulatory sources...")
    print("="*60)
    test_sources()

    # Step 4: Instructions
    print("\n" + "="*60)
    print("  ✅ Setup complete!")
    print("="*60)
    print("""
Next steps:

  1. Run the agent now:
     python agents/orchestrator.py

  2. You should see publications analyzed by Gemini
     and an email sent to your inbox

  3. If email doesn't arrive, check your spam folder
     or verify your Gmail App Password is correct

  4. To run daily automatically:
     python agents/scheduler.py

  5. For the full dashboard:
     uvicorn backend.main:app --reload --port 8000
     Then open: frontend/index.html in your browser

Questions? The README has full troubleshooting.
""")


if __name__ == "__main__":
    main()
